name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        shell: cmd
        run: pip install pyinstaller customtkinter reportlab

      - name: Verificar arquivos
        shell: cmd
        run: dir

      - name: Gerar EXE
        shell: cmd
        run: pyinstaller --onefile --windowed --name "Intelbras_Storage_Calculator" --collect-all customtkinter calculator.py

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: Intelbras_Storage_Calculator
          path: dist\Intelbras_Storage_Calculator.exe
          if-no-files-found: error
